import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

// Release signing comes from CI secrets when present. Without them (forks, local
// builds, the default GitHub Actions run) the release build is signed with the
// debug key so the artifact is still installable. See DECISIONS.md.
val releaseKeystore: String? = System.getenv("PT_KEYSTORE")?.takeIf { it.isNotBlank() }

android {
    namespace = "io.github.kaustubhowmick.plaintext"
    compileSdk = 36

    defaultConfig {
        applicationId = "io.github.kaustubhowmick.plaintext"
        minSdk = 26
        targetSdk = 36
        versionCode = 2
        versionName = "1.0.1"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    // English only for v1.
    androidResources {
        localeFilters += listOf("en")
    }

    signingConfigs {
        if (releaseKeystore != null) {
            create("release") {
                storeFile = file(releaseKeystore)
                storePassword = System.getenv("PT_KEYSTORE_PASSWORD")
                keyAlias = System.getenv("PT_KEY_ALIAS")
                keyPassword = System.getenv("PT_KEY_PASSWORD")
                enableV1Signing = false   // minSdk 26: v2/v3 only, no META-INF signature files
                enableV2Signing = true
                enableV3Signing = true
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true        // R8: shrink, optimize, obfuscate
            isShrinkResources = true      // remove unused resources
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = signingConfigs.getByName(if (releaseKeystore != null) "release" else "debug")
            vcsInfo.include = false       // no version-control-info.textproto in the APK
        }
        debug {
            applicationIdSuffix = ".debug"
        }
    }

    buildFeatures {
        buildConfig = false               // version read from PackageManager
        resValues = false
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += listOf(
                "META-INF/*.kotlin_module",
                "META-INF/*.version",
                "META-INF/**/LICENSE*",
                "META-INF/**/NOTICE*",
                "kotlin/**",
                "DebugProbesKt.bin",
            )
        }
    }

    // No dependency metadata block: there are no third-party dependencies to report.
    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }

    lint {
        abortOnError = true
        checkReleaseBuilds = true
        warningsAsErrors = false
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
        // Drop Intrinsics null-check calls from generated bytecode: smaller dex.
        freeCompilerArgs.addAll(
            "-Xno-param-assertions",
            "-Xno-call-assertions",
            "-Xno-receiver-assertions",
        )
    }
}

dependencies {
    // Runtime: none (kotlin-stdlib is added by the Kotlin plugin and shrunk by R8).

    testImplementation("junit:junit:4.13.2")
}

// Fails the build if anything other than the Kotlin standard library (and its
// JetBrains annotations) lands on the release runtime classpath (design.md §11.5).
configurations.matching { it.name == "releaseRuntimeClasspath" }.configureEach {
    incoming.afterResolve {
        val extra = resolutionResult.allComponents
            .map { it.id }
            .filterIsInstance<org.gradle.api.artifacts.component.ModuleComponentIdentifier>()
            .filterNot { it.group == "org.jetbrains.kotlin" || it.group == "org.jetbrains" }
        check(extra.isEmpty()) { "Unexpected runtime dependencies: $extra — update design.md §2.3 first" }
    }
}
